can't remember what this was

diff --git a/bin/openscad-render b/bin/openscad-render
--- a/bin/openscad-render
+++ b/bin/openscad-render
@@ -57,6 +57,12 @@ process_all_comments() {
             output="output/${file%.*}_$module.$filetype"
         fi
 
+        if echo "$filetype" | grep -q "flatgif"; then
+            build_flat_gif "$file" "$module" $( echo "$output" | sed 's/flatgif/gif/') "$args" &
+            no_hits=0
+            continue
+        fi
+
         if echo "$filetype" | grep -q "gif"; then
             build_gif "$file" "$module" "$output" "$args" &
             no_hits=0
@@ -101,6 +107,44 @@ build_color() {
     wait
     $blender
 }
+
+build_flat_gif() {
+    file=$1
+    shift
+    module=$1
+    shift
+    output=$1
+    shift
+
+    # disabled args for gif
+
+    fps=$( echo "$args" | grep -o 'FPS [^ ]*' | grep -o '[0-9]*' || true )
+    [ -z "$fps" ] && fps=15
+
+    steps=$( echo "$@" | grep -o 'STEPS [^ ]*' | grep -o '[0-9]*' || true )
+    [ -z "$steps" ] && steps=90
+
+    delay=$( echo "100 / $fps" | bc -l )
+
+    frames=$( mktemp -d )
+    echo "Writing frames to $frames"
+
+    # shellcheck disable=SC2068
+    for step in $( seq 0 $steps ); do
+        t=$( echo "1 / $steps * $step" | bc -l )
+        if ! time $openscad --camera=0,0,0,0,0,0,0 --viewall --autocenter --colorscheme="$colorscheme" -o "$frames/frame_$step.png" -D"\$t=$t" <( use_module_fifo "$file" "$module" ); then
+            echo "$output $step/$steps ${RED}failed$NORMAL"
+            return 1
+        fi
+        echo "${GREEN}$output $step/$steps$NORMAL"
+    done
+    if ! convert $( /bin/find "$frames" -name '*.png' | sort --version-sort ) -set delay "$delay" "$output"; then
+            echo "$output ${RED}failed$NORMAL"
+            return 1
+    fi
+    echo "$output ${GREEN}OK$NORMAL"
+}
+
 
 build_gif() {
     file=$1
@@ -220,7 +264,7 @@ execute() {
     dir=$( dirname "$file" )
     out=$dir/output
     mkdir -p "$out"
-    process_all_comments "$file" || true # process_one "$file" 
+    process_all_comments "$file" || process_one "$file" 
     wait
     # git commit -m "autogen outout"
     echo ""
